# fly.toml app configuration file generated for rd on 2023-05-24T00:11:31+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rd"
primary_region = "sin"

[env]
LIBREDDIT_DEFAULT_SHOW_NSFW="on"
LIBREDDIT_DEFAULT_USE_HLS="on"
LIBREDDIT_DEFAULT_THEME="doomone"
LIBREDDIT_BANNER="hehe"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
